# Intro to Machine Learning Homework 3

### Bryce Readyhough 
### ID-801005029

Importing the dataset. This will be used for all 4 problems in the homework. In this case the dataset will be downloaded from SKlearn rather than imported from a CSV like previous homeworks have been.

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.datasets import load_breast_cancer #Importing the breast cancer dataset

In [4]:
breast = load_breast_cancer()

In [5]:
breast_data = breast.data
breast_data.shape

(569, 30)

In [7]:
breast_input = pd.DataFrame(breast_data)
breast_input.head()

0      1       2       3        4        5       6        7       8   \
0  17.99  10.38  122.80  1001.0  0.11840  0.27760  0.3001  0.14710  0.2419   
1  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.0869  0.07017  0.1812   
2  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.1974  0.12790  0.2069   
3  11.42  20.38   77.58   386.1  0.14250  0.28390  0.2414  0.10520  0.2597   
4  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.1980  0.10430  0.1809   

        9   ...     20     21      22      23      24      25      26      27  \
0  0.07871  ...  25.38  17.33  184.60  2019.0  0.1622  0.6656  0.7119  0.2654   
1  0.05667  ...  24.99  23.41  158.80  1956.0  0.1238  0.1866  0.2416  0.1860   
2  0.05999  ...  23.57  25.53  152.50  1709.0  0.1444  0.4245  0.4504  0.2430   
3  0.09744  ...  14.91  26.50   98.87   567.7  0.2098  0.8663  0.6869  0.2575   
4  0.05883  ...  22.54  16.67  152.20  1575.0  0.1374  0.2050  0.4000  0.1625   

       28       29  
0  0.4601  0.11890  
1  0.2750  0.08902  
2  0.3613  0.08758  
3  0.6638  0.17300  
4  0.2364  0.07678  

[5 rows x 30 columns]

In [8]:
breast_labels = breast.target

In [9]:
breast_labels.shape

(569,)

In [10]:
labels = np.reshape(breast_labels,(569,1))

In [14]:
final_breast_data = np.concatenate([breast_data,labels],axis=1)
final_breast_data.shape

(569, 31)

In [15]:
breast_dataset = pd.DataFrame(final_breast_data)

In [19]:
features = breast.feature_names
features

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [20]:
feature_labels = np.append(features,'label')
breast_dataset.columns = feature_labels
breast_dataset.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  label  
0          0.4601                  0.11890    0.0  
1          0.2750                  0.08902    0.0  
2          0.3613                  0.08758    0.0  
3          0.6638                  0.17300    0.0  
4          0.2364                  0.07678    0.0  

[5 rows x 31 columns]

In [21]:
breast_dataset['label'].replace(0, 'Benign',inplace=True)
breast_dataset['label'].replace(1, 'Malignant',inplace=True)

In [22]:
breast_dataset.tail()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
564                 0.05623  ...          26.40           166.10      2027.0   
565                 0.05533  ...          38.25           155.00      1731.0   
566                 0.05648  ...          34.12           126.70      1124.0   
567                 0.07016  ...          39.42           184.60      1821.0   
568                 0.05884  ...          30.37            59.16       268.6   

     worst smoothness  worst compactness  worst concavity  \
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     worst concave points  worst symmetry  worst fractal dimension      label  
564                0.2216          0.2060                  0.07115     Benign  
565                0.1628          0.2572                  0.06637     Benign  
566                0.1418          0.2218                  0.07820     Benign  
567                0.2650          0.4087                  0.12400     Benign  
568                0.0000          0.2871                  0.07039  Malignant  

[5 rows x 31 columns]

## Problem 1
For problem 1 we will be training a Logistic Regression using all 30 features of this dataset. With 30 features and only about 600 samples it is not expected that this model will perform well. We will be using a split of 80% of the data in the training set and 20% in the validation set. The dataset was also scaled using input Standardization.

In [38]:
X1 = breast_dataset.iloc[:,0:30].values
Y1 = breast_dataset.iloc[:,30].values

In [41]:
X1[0:5]

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
        3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
        8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
        3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
        1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02, 7.864e-02,
        8.690e-02, 7.017e-02, 1.812e-01, 5.667e-02, 5.435e-01, 7.339e-01,
        3.398e+00, 7.408e+01, 5.225e-03, 1.308e-02, 1.860e-02, 1.340e-02,
        1.389e-02, 3.532e-03, 2.499e+01, 2.341e+01, 1.588e+02, 1.956e+03,
        1.238e-01, 1.866e-01, 2.416e-01, 1.860e-01, 2.750e-01, 8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, 1.203e+03, 1.096e-01, 1.599e-01,
        1.974e-01, 1.279e-01, 2.069e-01, 5.999e-02, 7.456e-01, 7.869e-01,
        4.585e+00, 9.403e+01, 6.150e-03, 4.006e-02, 3.832e-02, 2.058e-02,
        2.250e-02, 4.571e-03, 2.357e

In [42]:
Y1[:5]

array(['Benign', 'Benign', 'Benign', 'Benign', 'Benign'], dtype=object)

In [43]:
from sklearn.model_selection import train_test_split
X1_train, X1_test, Y1_train, Y1_test = train_test_split(X1, Y1, test_size = 0.2, random_state = 1, shuffle = True)

In [45]:
from sklearn.preprocessing import StandardScaler
sc_X1 = StandardScaler()
X1_train = sc_X1.fit_transform(X1_train)
X1_test = sc_X1.fit_transform(X1_test)

In [50]:
X1_train[:3]

array([[ 1.0449852 ,  0.29708512,  1.01044815,  0.90312805,  0.52642027,
         0.4880825 ,  0.37978142,  0.98174683,  0.66363209, -0.30258962,
         0.14280677, -0.6119946 ,  0.06991346,  0.16634175,  0.07008426,
         0.10582633, -0.2324402 ,  0.46455558, -0.77103134, -0.17532873,
         0.93209962, -0.04698312,  0.85738005,  0.75490595,  0.72463229,
         0.75892743,  0.28422474,  1.21839781,  0.29811854,  0.08380738],
       [ 1.68141074, -1.14098169,  1.70338066,  1.74602236,  0.28608701,
         0.53430768,  1.35140244,  1.3896859 , -0.00849186, -0.57977321,
         1.2000442 , -0.77219008,  1.2032503 ,  1.08653332,  1.46300382,
        -0.06600412,  0.85874485,  1.10925417, -0.35741438,  0.46779799,
         1.22361704, -1.43818028,  1.26241867,  1.13504221,  0.23738755,
        -0.3306253 ,  0.62678932,  0.69716372, -0.88595033, -0.41234747],
       [-1.44260855, -1.12732916, -1.4504636 , -1.15482615, -1.91696783,
        -1.42332889, -1.0722744 , -1.17143992, -0

In [53]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=1)
classifier.fit(X1_train, Y1_train)
Y1_pred = classifier.predict(X1_test)
Y1_pred[0:9]

array(['Malignant', 'Benign', 'Malignant', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Malignant'], dtype=object)

In [54]:
from sklearn.metrics import confusion_matrix
cnf_matrix1 = confusion_matrix(Y1_test, Y1_pred)
cnf_matrix1

array([[40,  2],
       [ 1, 71]], dtype=int64)

In [57]:
from sklearn import metrics
print("Model 1 Accuracy: ", metrics.accuracy_score(Y1_test, Y1_pred))

Model 1 Accuracy:  0.9736842105263158


## Problem 2
For problem 2 another logistic regression was run. However, this time PCA feature extraction was used first to reduce the number of features. This is done to help improve the algorithm accuracy when the number of samples is low. 